In [1]:
import pandas as pd
import spotipy.util as util
import spotipy
%run "../Experiments/Utils.ipynb"

In [2]:
token = util.prompt_for_user_token('31z7enbknuggbtpidrsxziofxmlm','user-library-read',client_id='87b4599f0c0a4eb8bb6d8f6e3528df94',client_secret='3f93fff3d1ce434ea325760554fb772e',redirect_uri='http://localhost:8080')
sp = spotipy.Spotify(auth=token)

In [18]:
songs = pd.read_csv('../Experiments/data/batchSongs.csv')
songs = songs.drop(columns=['Unnamed: 0'])
songs['id_track'] = songs['id_track'].apply(lambda x: x.replace('.csv',''))
songs

,id_chord,id_track,chords,orig_key
0,6000001,3quIqeqcnQaiyM8X7kK7Wm,"C,C,C,C,Cm,G#,Cm,C,Cm,G#,F,Cm,C,C,A#,Cm,G#,D#,...",C#
1,6000002,7nq8DgNdgYGihJrZYB221C,"G#,E,C,C,G,Am,Em,F#m,Gm,C,Am,C,E,F#m,E,C,D,C,D...",D#
2,6000003,54T6BKSPCO5NcFXHzrSb9W,"C,F,G#,G#,A#,G,Cm,F,G#,Fm,A#,G,C,D,G#,B,A#,D#,...",A
3,6000004,2CVf3ApXLk1cXQ2B6Z9ZlS,"C,Cm,F,C,Cm,F,Cm,A#,Cm,F,A#,Cm,A#,Cm,A#,Cm,F,C...",C#
4,6000005,4hbO390vbRE8dNVx3oCwaF,"Cm,G#,Cm,Fm,Cm,G,C,G#,Cm,Fm,D#,G,Cm,G#,Fm,G,Cm...",E
...,...,...,...,...
2495,6002496,6si71supnBUhddjR2FJc2L,"A#m,F,A,F,G,C,Am,G,Am,Dm,Am,G,Am,F,G,Am,F,C,Am...",B
2496,6002497,3yUcJwYu7fXAfqMj9krY6l,"Dm,Gm,C,Am,Dm,Gm,C,A#,Dm,C,A#,C,F,A#,C,F,A#,C,...",G#
2497,6002498,4VrWlk8IQxevMvERoX08iC,"C#,F#m,Cm,F#,C#m,F#,C#,F#,C,F#,C#m,F#,F#,Bm,Cd...",A#
2498,6002499,2rW17Yz3pncp87DU20jBZ7,"Bm,C,Bm,C,G,B,C#m,C,D,D#,C#,Bm,A#,C,G,B,C,E,C#...",D#
2499,6002500,4058DPUoC7sLPQ05pr3e4C,"Am,Gm,A#,F,C,Dm,A#,F,C,Dm,A#,F,C,Dm,A#,F,C,A#,...",A#

In [19]:
songs = songs[songs.id_track != '5cY8y2XgOfkAh4kSWLFKkz']
songs

,id_chord,id_track,chords,orig_key
0,6000001,3quIqeqcnQaiyM8X7kK7Wm,"C,C,C,C,Cm,G#,Cm,C,Cm,G#,F,Cm,C,C,A#,Cm,G#,D#,...",C#
1,6000002,7nq8DgNdgYGihJrZYB221C,"G#,E,C,C,G,Am,Em,F#m,Gm,C,Am,C,E,F#m,E,C,D,C,D...",D#
2,6000003,54T6BKSPCO5NcFXHzrSb9W,"C,F,G#,G#,A#,G,Cm,F,G#,Fm,A#,G,C,D,G#,B,A#,D#,...",A
3,6000004,2CVf3ApXLk1cXQ2B6Z9ZlS,"C,Cm,F,C,Cm,F,Cm,A#,Cm,F,A#,Cm,A#,Cm,A#,Cm,F,C...",C#
4,6000005,4hbO390vbRE8dNVx3oCwaF,"Cm,G#,Cm,Fm,Cm,G,C,G#,Cm,Fm,D#,G,Cm,G#,Fm,G,Cm...",E
...,...,...,...,...
2495,6002496,6si71supnBUhddjR2FJc2L,"A#m,F,A,F,G,C,Am,G,Am,Dm,Am,G,Am,F,G,Am,F,C,Am...",B
2496,6002497,3yUcJwYu7fXAfqMj9krY6l,"Dm,Gm,C,Am,Dm,Gm,C,A#,Dm,C,A#,C,F,A#,C,F,A#,C,...",G#
2497,6002498,4VrWlk8IQxevMvERoX08iC,"C#,F#m,Cm,F#,C#m,F#,C#,F#,C,F#,C#m,F#,F#,Bm,Cd...",A#
2498,6002499,2rW17Yz3pncp87DU20jBZ7,"Bm,C,Bm,C,G,B,C#m,C,D,D#,C#,Bm,A#,C,G,B,C,E,C#...",D#
2499,6002500,4058DPUoC7sLPQ05pr3e4C,"Am,Gm,A#,F,C,Dm,A#,F,C,Dm,A#,F,C,Dm,A#,F,C,A#,...",A#

In [20]:
ids = []
for id in songs['id_track']:
    ids.append(id)

In [21]:
features = []
for id in ids:
    feature = sp.audio_features(id)
    features.append(feature)

In [22]:
featureDf = pd.DataFrame([s[0] for s in features],columns = ['id_spotify_track', 'id_track', 'danceability', 'energy', 'key',
       'loudness', 'mode', 'speechiness', 'acousticness', 'instrumentalness',
       'liveness', 'valence', 'tempo', 'duration_ms', 'time_signature', 'name',
       'popularity', 'album_name', 'release_date', 'year', 'mood'])
featureDf['id_spotify_track'] = ids

In [68]:
featureDf

,id_spotify_track,id_track,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,...,valence,tempo,duration_ms,time_signature,name,popularity,album_name,release_date,year,mood
0,3quIqeqcnQaiyM8X7kK7Wm,NaN,0.3430,0.267,1,-12.911,0,0.0314,0.9650,0.003140,...,0.1200,131.576,214079,4,NaN,NaN,NaN,NaN,NaN,NaN
1,7nq8DgNdgYGihJrZYB221C,NaN,0.7160,0.808,7,-5.677,0,0.3490,0.7270,0.000000,...,0.3910,76.022,211451,4,NaN,NaN,NaN,NaN,NaN,NaN
2,54T6BKSPCO5NcFXHzrSb9W,NaN,0.0994,0.554,9,-11.470,0,0.0550,0.5050,0.960000,...,0.0671,73.221,306101,4,NaN,NaN,NaN,NaN,NaN,NaN
3,2CVf3ApXLk1cXQ2B6Z9ZlS,NaN,0.1710,0.508,1,-8.857,0,0.0440,0.3290,0.006510,...,0.1610,199.888,194688,3,NaN,NaN,NaN,NaN,NaN,NaN
4,4hbO390vbRE8dNVx3oCwaF,NaN,0.5920,0.836,4,-3.818,0,0.0315,0.2820,0.002260,...,0.2000,102.539,364460,3,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2494,6si71supnBUhddjR2FJc2L,NaN,0.5090,0.537,5,-6.834,1,0.0384,0.3470,0.000007,...,0.3110,170.030,240040,4,NaN,NaN,NaN,NaN,NaN,NaN
2495,3yUcJwYu7fXAfqMj9krY6l,NaN,0.7250,0.583,1,-9.942,0,0.0427,0.3000,0.000238,...,0.7620,79.984,218360,4,NaN,NaN,NaN,NaN,NaN,NaN
2496,4VrWlk8IQxevMvERoX08iC,NaN,0.3990,0.787,1,-2.880,1,0.0499,0.0197,0.000061,...,0.5720,117.089,216120,5,NaN,NaN,NaN,NaN,NaN,NaN
2497,2rW17Yz3pncp87DU20jBZ7,NaN,0.3760,0.435,2,-7.584,0,0.0264,0.5130,0.025700,...,0.3040,80.002,232053,4,NaN,NaN,NaN,NaN,NaN,NaN
2498,4058DPUoC7sLPQ05pr3e4C,NaN,0.7340,0.663,10,-6.279,1,0.3090,0.3420,0.000000,...,0.8450,166.846,219573,4,NaN,NaN,NaN,NaN,NaN,NaN

In [23]:
for id,value in enumerate(ids):
    song = sp.audio_analysis(value)
    track = song['track']
    featureDf.at[id,'tempo'] = track['tempo']
    featureDf.at[id,'time_signature'] = track['time_signature']
    featureDf.at[id,'key'] = track['key']
    featureDf.at[id,'mode'] = track['mode']

In [69]:
featureDf['mode'].value_counts()

1    1489
0    1010
Name: mode, dtype: int64

In [70]:
#featureDf['id_chord']
songsM = songs[["id_chord","id_track"]]
songsM.rename(columns={'id_track':'id_spotify_track'},inplace=True)
songsM

C:\Users\fjorg\AppData\Local\Temp\ipykernel_7976\434657591.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  songsM.rename(columns={'id_track':'id_spotify_track'},inplace=True)

      id_chord        id_spotify_track
0      6000001  3quIqeqcnQaiyM8X7kK7Wm
1      6000002  7nq8DgNdgYGihJrZYB221C
2      6000003  54T6BKSPCO5NcFXHzrSb9W
3      6000004  2CVf3ApXLk1cXQ2B6Z9ZlS
4      6000005  4hbO390vbRE8dNVx3oCwaF
...        ...                     ...
2495   6002496  6si71supnBUhddjR2FJc2L
2496   6002497  3yUcJwYu7fXAfqMj9krY6l
2497   6002498  4VrWlk8IQxevMvERoX08iC
2498   6002499  2rW17Yz3pncp87DU20jBZ7
2499   6002500  4058DPUoC7sLPQ05pr3e4C

[2499 rows x 2 columns]

In [76]:
featureDf = pd.merge(featureDf,songsM, on='id_spotify_track')
featureDf

,id_spotify_track,id_track,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,...,tempo,duration_ms,time_signature,name,popularity,album_name,release_date,year,mood,id_chord
0,3quIqeqcnQaiyM8X7kK7Wm,NaN,0.3430,0.267,1,-12.911,0,0.0314,0.9650,0.003140,...,131.576,214079,4,NaN,NaN,NaN,NaN,NaN,NaN,6000001
1,7nq8DgNdgYGihJrZYB221C,NaN,0.7160,0.808,7,-5.677,0,0.3490,0.7270,0.000000,...,76.022,211451,4,NaN,NaN,NaN,NaN,NaN,NaN,6000002
2,54T6BKSPCO5NcFXHzrSb9W,NaN,0.0994,0.554,9,-11.470,0,0.0550,0.5050,0.960000,...,73.221,306101,4,NaN,NaN,NaN,NaN,NaN,NaN,6000003
3,2CVf3ApXLk1cXQ2B6Z9ZlS,NaN,0.1710,0.508,1,-8.857,0,0.0440,0.3290,0.006510,...,199.888,194688,3,NaN,NaN,NaN,NaN,NaN,NaN,6000004
4,4hbO390vbRE8dNVx3oCwaF,NaN,0.5920,0.836,4,-3.818,0,0.0315,0.2820,0.002260,...,102.539,364460,3,NaN,NaN,NaN,NaN,NaN,NaN,6000005
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2522,6si71supnBUhddjR2FJc2L,NaN,0.5090,0.537,5,-6.834,1,0.0384,0.3470,0.000007,...,170.030,240040,4,NaN,NaN,NaN,NaN,NaN,NaN,6002496
2523,3yUcJwYu7fXAfqMj9krY6l,NaN,0.7250,0.583,1,-9.942,0,0.0427,0.3000,0.000238,...,79.984,218360,4,NaN,NaN,NaN,NaN,NaN,NaN,6002497
2524,4VrWlk8IQxevMvERoX08iC,NaN,0.3990,0.787,1,-2.880,1,0.0499,0.0197,0.000061,...,117.089,216120,5,NaN,NaN,NaN,NaN,NaN,NaN,6002498
2525,2rW17Yz3pncp87DU20jBZ7,NaN,0.3760,0.435,2,-7.584,0,0.0264,0.5130,0.025700,...,80.002,232053,4,NaN,NaN,NaN,NaN,NaN,NaN,6002499
2526,4058DPUoC7sLPQ05pr3e4C,NaN,0.7340,0.663,10,-6.279,1,0.3090,0.3420,0.000000,...,166.846,219573,4,NaN,NaN,NaN,NaN,NaN,NaN,6002500

In [77]:

featureDf['mood'] = featureDf.apply(lambda x: setMoodLabel(x), axis=1)
featureDf['mood'] = featureDf.apply(lambda x: setMoodNumber(x), axis=1)
featureDf['mood']

0        2
1        7
2        3
3        3
4        4
        ..
2522     3
2523    10
2524     7
2525     2
2526    10
Name: mood, Length: 2527, dtype: int64

In [97]:
featureDf.drop_duplicates('id_spotify_track', inplace = True)
featureDf.reset_index(inplace=True)

,index,id_spotify_track,id_track,danceability,energy,key,loudness,mode,speechiness,acousticness,...,tempo,duration_ms,time_signature,name,popularity,album_name,release_date,year,mood,id_chord
0,0,3quIqeqcnQaiyM8X7kK7Wm,NaN,0.3430,0.267,1,-12.911,0,0.0314,0.9650,...,131.576,214079,4,NaN,NaN,NaN,NaN,NaN,2,6000001
1,1,7nq8DgNdgYGihJrZYB221C,NaN,0.7160,0.808,7,-5.677,0,0.3490,0.7270,...,76.022,211451,4,NaN,NaN,NaN,NaN,NaN,7,6000002
2,2,54T6BKSPCO5NcFXHzrSb9W,NaN,0.0994,0.554,9,-11.470,0,0.0550,0.5050,...,73.221,306101,4,NaN,NaN,NaN,NaN,NaN,3,6000003
3,3,2CVf3ApXLk1cXQ2B6Z9ZlS,NaN,0.1710,0.508,1,-8.857,0,0.0440,0.3290,...,199.888,194688,3,NaN,NaN,NaN,NaN,NaN,3,6000004
4,4,4hbO390vbRE8dNVx3oCwaF,NaN,0.5920,0.836,4,-3.818,0,0.0315,0.2820,...,102.539,364460,3,NaN,NaN,NaN,NaN,NaN,4,6000005
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2492,2492,6si71supnBUhddjR2FJc2L,NaN,0.5090,0.537,5,-6.834,1,0.0384,0.3470,...,170.030,240040,4,NaN,NaN,NaN,NaN,NaN,3,6002496
2493,2493,3yUcJwYu7fXAfqMj9krY6l,NaN,0.7250,0.583,1,-9.942,0,0.0427,0.3000,...,79.984,218360,4,NaN,NaN,NaN,NaN,NaN,10,6002497
2494,2494,4VrWlk8IQxevMvERoX08iC,NaN,0.3990,0.787,1,-2.880,1,0.0499,0.0197,...,117.089,216120,5,NaN,NaN,NaN,NaN,NaN,7,6002498
2495,2495,2rW17Yz3pncp87DU20jBZ7,NaN,0.3760,0.435,2,-7.584,0,0.0264,0.5130,...,80.002,232053,4,NaN,NaN,NaN,NaN,NaN,2,6002499
2496,2496,4058DPUoC7sLPQ05pr3e4C,NaN,0.7340,0.663,10,-6.279,1,0.3090,0.3420,...,166.846,219573,4,NaN,NaN,NaN,NaN,NaN,10,6002500

In [100]:
featureDf

,id_spotify_track,id_track,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,...,tempo,duration_ms,time_signature,name,popularity,album_name,release_date,year,mood,id_chord
0,3quIqeqcnQaiyM8X7kK7Wm,NaN,0.3430,0.267,1,-12.911,0,0.0314,0.9650,0.003140,...,131.576,214079,4,NaN,NaN,NaN,NaN,NaN,2,6000001
1,7nq8DgNdgYGihJrZYB221C,NaN,0.7160,0.808,7,-5.677,0,0.3490,0.7270,0.000000,...,76.022,211451,4,NaN,NaN,NaN,NaN,NaN,7,6000002
2,54T6BKSPCO5NcFXHzrSb9W,NaN,0.0994,0.554,9,-11.470,0,0.0550,0.5050,0.960000,...,73.221,306101,4,NaN,NaN,NaN,NaN,NaN,3,6000003
3,2CVf3ApXLk1cXQ2B6Z9ZlS,NaN,0.1710,0.508,1,-8.857,0,0.0440,0.3290,0.006510,...,199.888,194688,3,NaN,NaN,NaN,NaN,NaN,3,6000004
4,4hbO390vbRE8dNVx3oCwaF,NaN,0.5920,0.836,4,-3.818,0,0.0315,0.2820,0.002260,...,102.539,364460,3,NaN,NaN,NaN,NaN,NaN,4,6000005
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2492,6si71supnBUhddjR2FJc2L,NaN,0.5090,0.537,5,-6.834,1,0.0384,0.3470,0.000007,...,170.030,240040,4,NaN,NaN,NaN,NaN,NaN,3,6002496
2493,3yUcJwYu7fXAfqMj9krY6l,NaN,0.7250,0.583,1,-9.942,0,0.0427,0.3000,0.000238,...,79.984,218360,4,NaN,NaN,NaN,NaN,NaN,10,6002497
2494,4VrWlk8IQxevMvERoX08iC,NaN,0.3990,0.787,1,-2.880,1,0.0499,0.0197,0.000061,...,117.089,216120,5,NaN,NaN,NaN,NaN,NaN,7,6002498
2495,2rW17Yz3pncp87DU20jBZ7,NaN,0.3760,0.435,2,-7.584,0,0.0264,0.5130,0.025700,...,80.002,232053,4,NaN,NaN,NaN,NaN,NaN,2,6002499
2496,4058DPUoC7sLPQ05pr3e4C,NaN,0.7340,0.663,10,-6.279,1,0.3090,0.3420,0.000000,...,166.846,219573,4,NaN,NaN,NaN,NaN,NaN,10,6002500

In [101]:
featureDf.to_csv('../Experiments/data/BatchSongsSpotifyFeatures.csv')