In [1]:
import sqlite3

try:
    sqliteConnection = sqlite3.connect('../Databases/UltimateGuitarTabs.db')
    cursor = sqliteConnection.cursor()
    print("Database created and Successfully Connected to SQLite")

    sqlite_select_Query = "select sqlite_version();"
    cursor.execute(sqlite_select_Query)
    record = cursor.fetchall()
    print("SQLite Database Version is: ", record)
    cursor.close()

except sqlite3.Error as error:
    print("Error while connecting to sqlite", error)
finally:
    if sqliteConnection:
        sqliteConnection.close()
        print("The SQLite connection is closed")

Database created and Successfully Connected to SQLite
SQLite Database Version is:  [('3.38.5',)]
The SQLite connection is closed

In [2]:
import pandas as pd

### Regardless of the DB Engine fill df variable

In [3]:

try:
    sqliteConnection = sqlite3.connect('../Databases/UltimateGuitarTabs.db')
    cursor = sqliteConnection.cursor()
    print("Database created and Successfully Connected to SQLite")
    
    df = pd.read_sql_query('select * from Clean_Chords', sqliteConnection)
    
    sqlite_select_Query = "select sqlite_version();"
    cursor.execute(sqlite_select_Query)
    record = cursor.fetchall()
    print("SQLite Database Version is: ", record)
    cursor.close()

except sqlite3.Error as error:
    print("Error while connecting to sqlite", error)
finally:
    if sqliteConnection:
        sqliteConnection.close()
        print("The SQLite connection is closed")

Database created and Successfully Connected to SQLite
SQLite Database Version is:  [('3.38.5',)]
The SQLite connection is closed

In [4]:
df

          id orig_key                                             chords
0         23        E  Cm,C,A#,F,F,G,G,Cm,Cm,C,A#,F,F,F,F,Cm,G,G,G,G,...
1         73        G  C,F,F,C,F,C,F,F,C,F,C,F,F,C,F,C,F,C,C,Em,F,Dm,...
2         74        G  C,F,C,C,F,C,F,C,F,C,G,F,C,C,F,C,C,F,C,F,F,Dm,F...
3        105        C  C,C,C,C,C,C,A#,F,C,G,D,F,C,G,D,F,C,G,D,F,C,G,D...
4        118        G  A,F,G,C,D,D,C,G,F,D,C,G,F,D,C,F,D,C,F,D,C,F,D,...
..       ...      ...                                                ...
995  2859782        C  F,G,C,Dm,F,G,C,Am,Am,G,C,Em,F,Am,G,C,Em,F,F,G,...
996  2895911        C  Dm,Am,C,G,Dm,Am,C,G,Dm,Am,C,G,Dm,Am,C,G,Dm,Am,...
997  2898572        D  C,C,Am,F,G,G,C,Am,F,G,G,C,G,Am,F,G,C,G,Am,F,G,...
998  3034029        C  C,Em,Am,F,Fm,C,Em,Am,F,Fm,C,Em,Am,F,Fm,C,Em,Am...
999  3504560        G  C,Am,F,C,C,Am,F,C,F,C,F,C,Am,G,C,Em,F,F,G,C,C,...

[1000 rows x 3 columns]

### Checking list of chords

In [5]:
df.head(5)

    id orig_key                                             chords
0   23        E  Cm,C,A#,F,F,G,G,Cm,Cm,C,A#,F,F,F,F,Cm,G,G,G,G,...
1   73        G  C,F,F,C,F,C,F,F,C,F,C,F,F,C,F,C,F,C,C,Em,F,Dm,...
2   74        G  C,F,C,C,F,C,F,C,F,C,G,F,C,C,F,C,C,F,C,F,F,Dm,F...
3  105        C  C,C,C,C,C,C,A#,F,C,G,D,F,C,G,D,F,C,G,D,F,C,G,D...
4  118        G  A,F,G,C,D,D,C,G,F,D,C,G,F,D,C,F,D,C,F,D,C,F,D,...

In [6]:
keys = {}

for c in df['chords']:
    for symbol in c.split(','):
        if symbol not in keys: 
            keys[symbol] = 1
        else:
            keys[symbol] += 1

In [7]:
a = list(keys.keys())

In [8]:
a.sort()

In [9]:
listKeys = ['C',
 'C#',
 'C#dim',
 'C#m',
 'Cdim',
 'Cm',
 'D',
 'D#',
 'D#dim',
 'D#m',
 'Ddim',
 'Dm',
 'E',
 'Edim',
 'Em',
 'F',
 'F#',
 'F#dim',
 'F#m',
 'Fdim',
 'Fm',
 'G',
 'G#',
 'G#dim',
 'G#m',
 'Gm',
 'A',
 'A#',
 'A#dim',
 'A#m',
 'Adim',
 'Am',
 'B',
 'Bdim',
 'Bm']

In [10]:
chordsDF = pd.DataFrame(columns= listKeys)

In [11]:
keyMapper = {}
for key in listKeys:
    if key not in keyMapper:
        keyMapper[key] = 0

In [12]:
chordsDF

Empty DataFrame
Columns: [C, C#, C#dim, C#m, Cdim, Cm, D, D#, D#dim, D#m, Ddim, Dm, E, Edim, Em, F, F#, F#dim, F#m, Fdim, Fm, G, G#, G#dim, G#m, Gm, A, A#, A#dim, A#m, Adim, Am, B, Bdim, Bm]
Index: []

[0 rows x 35 columns]

In [13]:
import copy


## Going through all songs and mapping its chrods in C major to the table frame 

for c in df['chords']:
    keyMapperCopy = copy.deepcopy(keyMapper)

    for symbol in c.split(','):
        keyMapperCopy[symbol] += 1
    chordsDF = chordsDF.append(keyMapperCopy, ignore_index=True)

In [14]:
chordsDF

,C,C#,C#dim,C#m,Cdim,Cm,D,D#,D#dim,D#m,...,Gm,A,A#,A#dim,A#m,Adim,Am,B,Bdim,Bm
0,2,0,0,0,0,5,0,0,0,0,...,0,0,2,0,0,0,0,0,0,0
1,66,0,0,0,0,7,40,27,0,0,...,20,4,28,0,0,0,39,0,0,24
2,97,0,0,0,0,3,24,18,0,0,...,2,26,42,0,2,0,15,0,0,0
3,11,0,0,0,0,0,5,0,0,0,...,0,0,1,0,0,0,0,0,0,0
4,19,0,0,0,0,0,21,6,0,0,...,0,8,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,19,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,17,0,0,0
996,16,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,17,0,0,0
997,14,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,13,0,0,0
998,9,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,9,0,0,0
999,21,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,11,0,0,0

In [15]:
keyMapperCopy = copy.deepcopy(keyMapper)

In [16]:
keyMapperCopy['C'] +=1

In [17]:
chordsDF

,C,C#,C#dim,C#m,Cdim,Cm,D,D#,D#dim,D#m,...,Gm,A,A#,A#dim,A#m,Adim,Am,B,Bdim,Bm
0,2,0,0,0,0,5,0,0,0,0,...,0,0,2,0,0,0,0,0,0,0
1,66,0,0,0,0,7,40,27,0,0,...,20,4,28,0,0,0,39,0,0,24
2,97,0,0,0,0,3,24,18,0,0,...,2,26,42,0,2,0,15,0,0,0
3,11,0,0,0,0,0,5,0,0,0,...,0,0,1,0,0,0,0,0,0,0
4,19,0,0,0,0,0,21,6,0,0,...,0,8,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,19,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,17,0,0,0
996,16,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,17,0,0,0
997,14,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,13,0,0,0
998,9,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,9,0,0,0
999,21,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,11,0,0,0

In [24]:
X = chordsDF.values.tolist()

## Applying K-means Clustering
Inspired from [this article](https://medium.com/towards-data-science/k-means-clustering-unsupervised-learning-for-recommender-systems-397d3790f90f)

In [25]:
import dask_ml.cluster

km = dask_ml.cluster.KMeans(n_clusters=8, oversampling_factor=5)
km.fit(X)

KMeans(oversampling_factor=5)

In [134]:
print(X.shape)

(1001, 35)

In [27]:
labels = list(km.labels_.compute())
labels

[1,
 5,
 5,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 3,
 0,
 1,
 0,
 0,
 1,
 0,
 6,
 1,
 1,
 5,
 3,
 4,
 3,
 4,
 2,
 0,
 2,
 1,
 3,
 1,
 1,
 2,
 0,
 3,
 7,
 0,
 2,
 2,
 3,
 4,
 0,
 0,
 0,
 0,
 1,
 1,
 3,
 3,
 1,
 1,
 0,
 3,
 1,
 1,
 3,
 1,
 1,
 3,
 1,
 0,
 0,
 1,
 1,
 3,
 1,
 2,
 1,
 2,
 5,
 2,
 3,
 2,
 0,
 0,
 5,
 4,
 1,
 4,
 0,
 2,
 1,
 0,
 2,
 2,
 2,
 1,
 0,
 2,
 0,
 4,
 4,
 1,
 1,
 1,
 3,
 3,
 1,
 0,
 1,
 1,
 3,
 2,
 1,
 0,
 3,
 1,
 0,
 0,
 1,
 2,
 2,
 1,
 1,
 3,
 2,
 4,
 1,
 0,
 1,
 1,
 7,
 1,
 2,
 3,
 1,
 4,
 5,
 4,
 1,
 1,
 2,
 3,
 3,
 0,
 1,
 3,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 3,
 0,
 1,
 2,
 3,
 1,
 1,
 0,
 1,
 1,
 2,
 1,
 1,
 2,
 3,
 0,
 3,
 2,
 1,
 1,
 1,
 4,
 1,
 3,
 1,
 1,
 4,
 1,
 4,
 3,
 1,
 2,
 2,
 1,
 1,
 1,
 3,
 2,
 1,
 3,
 2,
 1,
 2,
 0,
 1,
 1,
 4,
 2,
 1,
 2,
 3,
 3,
 3,
 1,
 1,
 1,
 3,
 1,
 0,
 0,
 2,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 3,
 1,
 1,
 3,
 4,
 0,
 1,
 1,
 0,
 2,
 0,
 1,
 2,
 2,
 0,
 1,
 5,
 0,
 0,
 0,
 3,
 5,
 2,
 0,
 1,
 0,
 1,
 2,
 3,
 1,
 1,
 4,
 0,
 1,
 2,
 2,
 1,
 1,
 4,
 1,
 1,
 1,
 1,
 3,
 3,
 3,
 1,
 1,
 3,
 2,
 3,
 2,
 0,
 2,
 1,
 1,
 0,
 0,
 5,
 3,
 1,
 4,
 3,
 4,
 0,
 1,
 3,
 0,
 0,
 2,
 2,
 4,
 2,
 1,
 1,
 0,
 1,
 3,
 1,
 1,
 3,
 2,
 2,
 4,
 1,
 0,
 2,
 1,
 0,
 1,
 2,
 1,
 4,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 0,
 2,
 2,
 2,
 1,
 1,
 1,
 3,
 2,
 1,
 3,
 1,
 2,
 3,
 3,
 3,
 1,
 1,
 2,
 1,
 2,
 5,
 0,
 2,
 0,
 2,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 3,
 1,
 2,
 1,
 2,
 2,
 1,
 2,
 2,
 1,
 4,
 1,
 0,
 2,
 2,
 1,
 1,
 3,
 2,
 1,
 3,
 2,
 2,
 4,
 1,
 1,
 3,
 0,
 1,
 1,
 2,
 1,
 2,
 2,
 1,
 2,
 2,
 1,
 4,
 3,
 0,
 3,
 2,
 1,
 1,
 3,
 1,
 4,
 2,
 3,
 1,
 2,
 0,
 1,
 5,
 2,
 1,
 2,
 2,
 1,
 1,
 2,
 1,
 3,
 1,
 3,
 4,
 1,
 2,
 2,
 1,
 2,
 1,
 0,
 2,
 1,
 2,
 1,
 3,
 3,
 3,
 3,
 1,
 3,
 2,
 2,
 4,
 1,
 1,
 2,
 3,
 3,
 2,
 4,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 2,
 1,
 2,
 1,
 0,
 4,
 3,
 1,
 1,
 2,
 2,
 1,
 2,
 2,
 1,
 1,
 2,
 2,
 3,
 1,
 1,
 1,
 2,
 2,
 5,
 4,
 2,
 1,
 2,
 2,
 4,
 0,
 1,
 4,
 2,
 2,
 1,
 1,
 2,
 3,
 3,
 0,
 1,
 1,
 4,
 1,
 1,
 2,
 0,
 1,
 7,
 2,
 1,
 1,
 1,
 0,
 2,
 0,
 2,
 0,
 1,
 1,
 3,
 1,
 1,
 0,
 2,
 2,
 4,
 4,
 2,
 4,
 4,
 0,
 1,
 1,
 1,
 4,
 1,
 1,
 1,
 2,
 2,
 1,
 0,
 5,
 3,
 1,
 1,
 2,
 2,
 1,
 3,
 2,
 2,
 0,
 1,
 2,
 1,
 1,
 0,
 1,
 0,
 3,
 3,
 1,
 3,
 4,
 1,
 2,
 1,
 3,
 0,
 2,
 0,
 2,
 3,
 3,
 1,
 3,
 1,
 0,
 1,
 2,
 3,
 1,
 4,
 3,
 2,
 3,
 1,
 7,
 1,
 2,
 2,
 2,
 2,
 4,
 1,
 2,
 0,
 1,
 1,
 2,
 0,
 1,
 0,
 3,
 3,
 2,
 3,
 2,
 0,
 2,
 2,
 2,
 4,
 2,
 0,
 2,
 3,
 2,
 2,
 2,
 3,
 1,
 2,
 2,
 3,
 1,
 3,
 1,
 1,
 2,
 1,
 2,
 2,
 0,
 2,
 2,
 3,
 3,
 1,
 0,
 1,
 3,
 2,
 4,
 3,
 1,
 1,
 4,
 5,
 5,
 4,
 2,
 0,
 1,
 3,
 1,
 0,
 2,
 1,
 1,
 3,
 2,
 4,
 1,
 2,
 0,
 5,
 5,
 2,
 1,
 2,
 0,
 1,
 1,
 7,
 1,
 3,
 2,
 1,
 3,
 0,
 0,
 5,
 3,
 3,
 2,
 3,
 7,
 1,
 2,
 3,
 1,
 1,
 2,
 1,
 1,
 1,
 2,
 3,
 2,
 1,
 4,
 4,
 2,
 1,
 2,
 2,
 3,
 1,
 0,
 2,
 1,
 2,
 3,
 1,
 2,
 3,
 0,
 2,
 0,
 2,
 2,
 2,
 2,
 2,
 2,
 1,
 4,
 4,
 2,
 0,
 2,
 0,
 4,
 1,
 4,
 0,
 4,
 2,
 0,
 2,
 4,
 3,
 2,
 2,
 1,
 2,
 1,
 4,
 3,
 2,
 3,
 4,
 1,
 2,
 1,
 2,
 2,
 4,
 1,
 4,
 0,
 2,
 1,
 2,
 2,
 1,
 2,
 4,
 2,
 3,
 2,
 2,
 2,
 4,
 2,
 2,
 2,
 1,
 4,
 2,
 3,
 1,
 4,
 4,
 2,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 1,
 0,
 2,
 2,
 2,
 2,
 2,
 2,
 4,
 2,
 3,
 3,
 2,
 1,
 1,
 1,
 2,
 2,
 2,
 4,
 2,
 2,
 4,
 2,
 1,
 4,
 1,
 1,
 2,
 2,
 1,
 2,
 1,
 2,
 2,
 2,
 3,
 5,
 4,
 0,
 1,
 2,
 1,
 4,
 2,
 1,
 1,
 2,
 0,
 1,
 1,
 2,
 2,
 1,
 1,
 1,
 3,
 3,
 4,
 3,
 1,
 2,
 1,
 2,
 2,
 2,
 4,
 1,
 2,
 0,
 2,
 1,
 1,
 3,
 0,
 2,
 2,
 1,
 1,
 1,
 2,
 1,
 0,
 2,
 1,
 2,
 2,
 1,
 0,
 4,
 1,
 3,
 2,
 2,
 2,
 1,
 2,
 2,
 4,
 4,
 1,
 0,
 3,
 1,
 2,
 2,
 2,
 1,
 2,
 2,
 4,
 2,
 1,
 3,
 2,
 3,
 2,
 2,
 3,
 7,
 7,
 2,
 2,
 2,
 2,
 1,
 1,
 2,
 1,
 1,
 1,
 2,
 5,
 2,
 2,
 2,
 2,
 1,
 1,
 7,
 1,
 2,
 2,
 4,
 0,
 2,
 1,
 3,
 5,
 2,
 1,
 1,
 4,
 0,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 3,
 1,
 1,
 2,
 2,
 1,
 2,
 1,
 3,
 2,
 1,
 1,
 2,
 1,
 1,
 1,
 2,
 2,
 2,
 0,
 2,
 2,
 0,
 1,
 2,
 2,
 3,
 2,
 3,
 1,
 2,
 3,
 3,
 1,
 1,
 1,
 1,
 3,
 2,
 1,
 2,
 3,
 1,
 2,
 1,
 1,
 1,
 1]

In [136]:
chordsDF.head()

,C,C#,C#dim,C#m,Cdim,Cm,D,D#,D#dim,D#m,...,Gm,A,A#,A#dim,A#m,Adim,Am,B,Bdim,Bm
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2,0,0,0,0,5,0,0,0,0,...,0,0,2,0,0,0,0,0,0,0
2,66,0,0,0,0,7,40,27,0,0,...,20,4,28,0,0,0,39,0,0,24
3,97,0,0,0,0,3,24,18,0,0,...,2,26,42,0,2,0,15,0,0,0
4,11,0,0,0,0,0,5,0,0,0,...,0,0,1,0,0,0,0,0,0,0